# Generated by Django 4.2.8 on 2023-12-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('grad_year', models.IntegerField(blank=True, null=True)),
                ('subject1', models.CharField(blank=True, max_length=32, null=True)),
                ('subject2', models.CharField(blank=True, max_length=32, null=True)),
                ('subject3', models.CharField(blank=True, max_length=32, null=True)),
                ('subject4', models.CharField(blank=True, max_length=32, null=True)),
                ('subject5', models.CharField(blank=True, max_length=32, null=True)),
                ('subject6', models.CharField(blank=True, max_length=32, null=True)),
                ('subject7', models.CharField(blank=True, max_length=32, null=True)),
                ('subject8', models.CharField(blank=True, max_length=32, null=True)),
                ('subject9', models.CharField(blank=True, max_length=32, null=True)),
                ('subject10', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
    ]
